#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json, sys
import openldap
records = openldap.export_users()
json.dump({
    "status": "success",
    "message": "users_exported",
    "records": records
}, fp=sys.stdout)
