#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json, sys
import openldap
req = json.load(sys.stdin)
records = req.get('records', [])
skip_existing = req.get('skip_existing', False)
success = openldap.import_users(records, skip_existing, progfunc=lambda x: None)
if success:
    json.dump({
        "status": "success",
        "message": "users_imported",
    }, fp=sys.stdout)
else:
    json.dump({
        "status": "failure",
        "message": "import_failed",
    }, fp=sys.stdout)
    sys.exit(1)
