#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import datetime
import json
import os
import sys

import agent

from agent.ldapproxy import Ldapproxy
from agent.ldapclient import Ldapclient

request = json.load(sys.stdin)

odomain = Ldapproxy().get_domain(os.environ["LDAP_DOMAIN"])
oldapcli = Ldapclient.factory(**odomain)

try:
    uentry = oldapcli.get_user_entry(
        os.environ["JWT_ID"],
        ["pwdChangedTime", "createTimestamp", "pwdPolicySubentry"],
    )
except agent.ldapclient.exceptions.LdapclientEntryNotFound:
    json.dump(
        {
            "status": "failure",
            "message": "user_not_found",
            "expired": False,
            "expiration": None,
            "must_change": False,
        },
        fp=sys.stdout,
    )
    sys.exit(0)

max_pwd_age = oldapcli.get_pwd_max_age()
pwd_policy_subentry = uentry["attributes"].get("pwdPolicySubentry") or ""
pwd_changed_time = uentry["attributes"].get(
    "pwdChangedTime",
    uentry["attributes"].get("createTimestamp", None),
)

expiration = None
expired = False

if not pwd_policy_subentry.startswith("cn=neverexpires,ou=PPolicy,") and max_pwd_age and pwd_changed_time:
    expiry_date = pwd_changed_time + datetime.timedelta(seconds=max_pwd_age)
    expired = datetime.datetime.now(datetime.timezone.utc) > expiry_date
    expiration = expiry_date.isoformat().replace("+00:00", "Z")

json.dump(
    {
        "status": "success",
        "message": "password_expiration",
        "expired": expired,
        "expiration": expiration,
        "must_change": False,
    },
    fp=sys.stdout,
)
