#!/bin/bash

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# - Define the "neverexpires" password policy, if it's missing.
# - If missing, apply also "neverexpires" to existing users that have no
#   pwdChangedTime attribute.
#
podman exec -i openldap ash -s <<'EOF'
{
  ldapsearch -QLLLo ldif_wrap=no -b "cn=default,ou=PPolicy,${LDAP_SUFFIX}" -s base | \
    sed  \
    -e 's/^dn: cn=default,/dn: cn=neverexpires,/' \
    -e '/^dn:/a changetype: add' \
    -e 's/^cn: default/cn: neverexpires/' \
    -e 's/^pwdMaxAge:.*/pwdMaxAge: 0/' \
    -e 's/^pwdExpireWarning:.*/pwdExpireWarning: 0/'
  ldapsearch -QLLLo ldif_wrap=no "(&(objectClass=inetOrgPerson)(!(pwdChangedTime=*))(!(pwdPolicySubentry=*)))" dn | \
    awk -v "ldap_suffix=${LDAP_SUFFIX}" '
    /^dn:/ {
        print $0
        print "changetype: modify"
        print "add: pwdPolicySubentry"
        print "pwdPolicySubentry: cn=neverexpires,ou=PPolicy," ldap_suffix
        print "-"
        print ""
    }'
} | ldapmodify -Q || :
EOF
