#!/bin/bash

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# - Define the "neverexpires" password policy, if it's missing.
#
podman exec -i openldap ash -s <<'EOF'
{
  ldapsearch -QLLLo ldif_wrap=no -b "cn=default,ou=PPolicy,${LDAP_SUFFIX}" -s base | \
    sed  \
    -e 's/^dn: cn=default,/dn: cn=neverexpires,/' \
    -e '/^dn:/a changetype: add' \
    -e 's/^cn: default/cn: neverexpires/' \
    -e 's/^pwdMaxAge:.*/pwdMaxAge: 0/' \
    -e 's/^pwdExpireWarning:.*/pwdExpireWarning: 0/'
} | ldapmodify -Q || :
EOF
