#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2
set -e

echo "Fix the default password policy"
podman exec -i openldap ldapadd -c <<EOF || :
dn: ou=PPolicy,${LDAP_SUFFIX}
objectClass: top
objectClass: organizationalUnit
ou: PPolicy

dn: cn=default,ou=PPolicy,${LDAP_SUFFIX}
objectClass: namedPolicy
objectClass: pwdPolicy
objectClass: pwdPolicyChecker
cn: default
pwdAttribute: userPassword
pwdCheckQuality: 2
pwdMinAge: 0
pwdMaxAge: 0
pwdMinLength: 0
pwdInHistory: 0
pwdLockout: TRUE
pwdUseCheckModule: FALSE
pwdCheckModuleArg: default
pwdExpireWarning: 0

dn: cn=neverexpires,ou=PPolicy,${LDAP_SUFFIX}
objectClass: namedPolicy
objectClass: pwdPolicy
objectClass: pwdPolicyChecker
cn: neverexpires
pwdAttribute: userPassword
pwdCheckQuality: 2
pwdMinAge: 0
pwdMaxAge: 0
pwdMinLength: 0
pwdInHistory: 0
pwdLockout: TRUE
pwdUseCheckModule: FALSE
pwdCheckModuleArg: default
pwdExpireWarning: 0
EOF

podman exec -i openldap ash -s <<'EOF'
{
  ldapsearch -QLLLo ldif_wrap=no "(&(objectClass=inetOrgPerson)(!(pwdChangedTime=*))(!(pwdPolicySubentry=*)))" dn | \
    awk -v "ldap_suffix=${LDAP_SUFFIX}" '
    /^dn:/ {
        print $0
        print "changetype: modify"
        print "add: pwdPolicySubentry"
        print "pwdPolicySubentry: cn=neverexpires,ou=PPolicy," ldap_suffix
        print "-"
        print ""
    }'
} | ldapmodify -c -Q || :
EOF

exit 0
