#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json, sys
import openldap
import agent
request = json.load(sys.stdin)
skip_existing = request.get('skip_existing', False)
records = request.get('records', [])
progcbk = agent.get_progress_callback(1,99)
cur = 0

def _prog(p):
    global cur
    v = int(p)
    if v > cur:
        progcbk(v)
        cur = v
success = openldap.import_users(records, skip_existing, progfunc=_prog)
if not success:
    sys.exit(1)
