#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json, sys
import openldap
response = {"records": openldap.export_users()}
json.dump(response, fp=sys.stdout)
